package com.mulesoft.training;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.InitializingBean;


public class Database implements InitializingBean {
    private static Logger logger = LoggerFactory.getLogger(Database.class);
    
    public void afterPropertiesSet() throws Exception {
       // String dbURL = "jdbc:MySQL:memory:muleEmbeddedDB;create=true";
        Connection conn = null;
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            conn = DriverManager.getConnection("jdbc:Mysql://localhost:3306/employee","root","whishworks_123");
            DatabaseMetaData md = conn.getMetaData();
            System.out.println("connection done");
            ResultSet rs = md.getTables(null, null, "%", null);
            logger.debug("&&&& - DB Init - &&&&");
            System.out.println("logger debug");
            int i=0;
            while (rs.next()){
                logger.debug("there is next " + rs.getString(3));
                if(rs.getString(3).equalsIgnoreCase("FLIGHTS")) i=1; //set a marker that this table already exists
            }
            logger.debug("&&&& - DB Init - &&&&");
            System.out.println("logger debug2");
            Statement stmt = conn.createStatement();
            if(i!=0){
            /*stmt.executeUpdate("CREATE TABLE employee.FLIGHTS(ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 0)  NOT NULL PRIMARY KEY," +
                    "PRICE INT," +
                    "DESTINATION VARCHAR(255)," +
                    "ORIGIN VARCHAR(255))");*/
            	System.out.println("befor query");
            stmt.executeUpdate("INSERT INTO FLIGHTS(PRICE, DESTINATION, ORIGIN) VALUES (555, 'SFO','YYZ')");
            stmt.executeUpdate("INSERT INTO FLIGHTS(PRICE, DESTINATION, ORIGIN) VALUES (450, 'LAX','YYZ')");
            stmt.executeUpdate("INSERT INTO FLIGHTS(PRICE, DESTINATION, ORIGIN) VALUES (777, 'SEA','SQL')");
            stmt.executeUpdate("INSERT INTO FLIGHTS(PRICE, DESTINATION, ORIGIN) VALUES (999, 'SFO','SQL')");
            }
            System.out.println("after query");
        } 
        catch (java.sql.SQLException sqle) {
            sqle.printStackTrace();
            throw sqle;
        }
    }
}